import { link } from "wesl";
import { uniformsWgsl, Vertex } from "./timefold-generated-wgsl";

console.log('Vertex definition generated by timefold');
console.log(Vertex.wgsl);

console.log('Uniforms and deduplicated Struct definitions generated by timefold');
console.log(uniformsWgsl);


export const getShaderModule = async (device: GPUDevice) => {
    const main = await fetch('./main.wesl').then(r => r.text());

    console.log('Wesl main module with imports');
    console.log(main);

    const wesl = await link({
        weslSrc: {
            'main.wesl': main,
            'vertex.wesl': Vertex.wgsl,
            'uniforms.wesl': uniformsWgsl,
        },
    });

    console.log('Final wgsl generated by wesl');
    console.log(wesl.dest);

    return wesl.createShaderModule(device, {});
}