/// <reference types="wesl-plugin/suffixes" />
import { link } from "wesl";
import linkMain from "../shaders/main.wesl?link";
import { uniformsWgsl, Vertex } from "./timefold-generated-wgsl";

console.log("Vertex definition generated by timefold");
console.log(Vertex.wgsl);

console.log(
  "Uniforms and deduplicated Struct definitions generated by timefold"
);
console.log(uniformsWgsl);

export const getShaderModule = async (device: GPUDevice) => {
  const virtualLibs = {
    vertex: () => Vertex.wgsl,
    uniforms: () => uniformsWgsl,
  };
  const wesl = await link({ ...linkMain, virtualLibs });
  console.log("Final wgsl generated by wesl");
  console.log(wesl.dest);

  return wesl.createShaderModule(device, {});
};
